### ISSUE TITLE
[MC 1.20.6] Update 1.1.0 causes game to crash during startup

### ISSUE THREAD

**Issue by Moravuscz** [KKW557/MoreCursors#4]
Hi,
after updating to 1.1.0 the game crashes for me.

Crash log: https://mclo.gs/xGtIdY8

Version 1.0.3 works fine.

**Comment by KKW557** [comment]
fixed [1.1.1](https://modrinth.com/mod/morecursors/version/1.1.1)

**Comment by Moravuscz** [comment]
Unfortunately no change with 1.1.1, still the same error.
![Image](https://github.com/user-attachments/assets/1097a6ea-7515-490a-8a6c-c947a966e84e)

**Comment by KKW557** [comment]
[40305f4](https://github.com/KKW557/MoreCursors/commit/40305f4cc4d8d08b47ca3f68ce356ec4bed69c07)

**Comment by Moravuscz** [comment]
Solved, thanks.
